---
- name: config_tftpd | ensuring tftp_directory exists
  file:
    dest: "{{ tftp_directory }}"
    state: directory
    owner: tftp
    group: tftp

- name: config_tftpd | configuring tftpd
  template:
    src: "etc/default/tftpd-hpa.j2"
    dest: "/etc/default/tftpd-hpa"
    owner: root
    group: root
    mode: 0644
  notify: restart tftpd-hpa

- name: config_tftpd | configuring inetd
  template:
    src: "etc/inetd.conf.j2"
    dest: "/etc/inetd.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart tftpd-hpa
